version: "3.7"
services:
  database:
    container_name: plum_pg
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      # copy the sql script to create tables
      - ./sql:/docker-entrypoint-initdb.d
